version: "1.0"
services:
  webapp:
    build: ../../webapp
    container_name: sfh_webapp
    ports:
     - "80:80"
  api:
    build: ../../sfh_api
    container_name: sfh_api
    ports:
      - "5000:5000"